"""The EDGE experiment model.

An experiment is a plain data document (YAML or JSON) so it can be produced by
the visual builder, written by hand, generated by scripts, diffed in git and
validated before anyone sits in front of a screen.

    name: Stroop
    settings: {window: {size: [1280, 720], background: "#202020"}}
    devices:
      - {id: et, type: gazepoint}
      - {id: lsl, type: lsl_markers}
    routines:
      trial:
        components:
          - {id: word, type: text, text: "$word", color: "$ink", start: 0.5}
          - {id: resp, type: keyboard, keys: [r, g, b], start: 0.5, end_routine: true,
             correct: "$correct_key"}
    flow:
      - instructions
      - loop: trials
        conditions: stroop.csv
        order: random
        repeats: 2
        children: [trial]

See docs/EXPERIMENT_FORMAT.md for the full reference.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Union

from . import expressions


DEFAULT_SETTINGS: dict[str, Any] = {
    "window": {
        "size": [1280, 720],
        "fullscreen": False,
        "screen": 0,
        "background": "#000000",
        "units": "px",           # px | norm | height | deg
        "refresh_rate": None,    # None = measure at startup
        "vsync": True,
        "monitor": {"width_cm": 53.0, "distance_cm": 60.0},
    },
    "data": {
        "dir": "data",
        "filename": "{participant}_{session}_{experiment}_{date}",
        "save_frame_log": True,
        "exports": ["csv"],      # also: xlsx, tsv, json, jsonl, parquet, mat, bids (written at session end)
        "summary": {},           # optional overrides: {by: [factor, ...], rt: comp.rt, correct: comp.corr}
    },
    "participant": {"participant": "001", "session": "1"},
    "timing": {
        "frame_drop_tolerance": 1.5,   # a frame is "dropped" if interval > tolerance * expected
    },
    "seed": None,
}

# Keys that belong to the component's scheduling rather than its properties.
SCHEDULE_KEYS = {
    "id", "type", "start", "start_frame", "start_after", "start_if",
    "duration", "duration_frames", "stop_if", "end_routine", "disabled", "save", "if",
}

# Actions allowed in routine rules ("when <condition> do <actions>").
RULE_ACTIONS = {"set", "end_routine", "start", "stop", "marker", "goto", "log"}


def deep_merge(base: dict, override: dict) -> dict:
    out = copy.deepcopy(base)
    for k, v in (override or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = copy.deepcopy(v)
    return out


def _bad(where: str, what: str, value: Any) -> "DocumentError":
    from .storage import DocumentError
    kind = {dict: "a mapping", list: "a list", str: "text", bool: "true/false", int: "a number", float: "a number",
            type(None): "empty"}.get(type(value), type(value).__name__)
    return DocumentError(f"{where}: expected {what}, got {kind}" + ("" if value is None else f" ({_short(value)})"))


def _short(v: Any, n: int = 60) -> str:
    text = repr(v)
    return text if len(text) <= n else text[:n - 1] + "…"


def _condition(value: Any, where: str) -> str | None:
    """A condition (``if``, ``when``): an expression string; true/false are accepted as they are."""
    if value is None or value == "":
        return None
    if isinstance(value, bool):
        return "$True" if value else "$False"
    if isinstance(value, (int, float)):
        return f"${value!r}"
    if not isinstance(value, str):
        raise _bad(where, "a condition (an expression such as $score > 3)", value)
    return value


def _mapping(value: Any, where: str, what: str = "a mapping (key: value lines)") -> dict[str, Any]:
    """``value`` as a dict with string keys, or a DocumentError saying where it is wrong."""
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise _bad(where, what, value)
    return {str(k): v for k, v in value.items()}


def _listing(value: Any, where: str, what: str = "a list (lines starting with -)") -> list[Any]:
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        return list(value)
    raise _bad(where, what, value)


@dataclass
class ComponentSpec:
    id: str
    type: str
    start: Any = 0.0
    start_frame: int | None = None
    start_after: str | None = None
    start_if: str | None = None
    duration: Any = None
    duration_frames: int | None = None
    stop_if: str | None = None
    end_routine: bool = False
    disabled: Any = False
    save: bool = True
    only_if: str | None = None   # YAML key "if": the component exists in this run only when true
    props: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, d: dict[str, Any], where: str = "component") -> "ComponentSpec":
        d = _mapping(d, where, "a component (a mapping with id and type)")
        props = {k: v for k, v in d.items() if k not in SCHEDULE_KEYS}
        return cls(
            id=str(d.get("id", "")),
            type=str(d.get("type", "")),
            start=d.get("start", 0.0),
            start_frame=d.get("start_frame"),
            start_after=d.get("start_after"),
            start_if=d.get("start_if"),
            duration=d.get("duration"),
            duration_frames=d.get("duration_frames"),
            stop_if=d.get("stop_if"),
            end_routine=bool(d.get("end_routine", False)),
            disabled=d.get("disabled", False),
            save=bool(d.get("save", True)),
            only_if=_condition(d.get("if"), f"{where}.if"),
            props=props,
        )

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"id": self.id, "type": self.type}
        defaults = ComponentSpec(id="", type="")
        for k in SCHEDULE_KEYS - {"id", "type"}:
            attr = "only_if" if k == "if" else k
            v = getattr(self, attr)
            if v != getattr(defaults, attr):
                d[k] = v
        d.update(self.props)
        return d


@dataclass
class Routine:
    id: str
    components: list[ComponentSpec] = field(default_factory=list)
    duration: Any = None      # hard cap in seconds (number or expression)
    end_if: str | None = None  # expression checked every frame
    description: str = ""
    # event rules checked every frame: [{when: "$resp.keys == 'q'", do: [{end_routine: true}], repeat: false}]
    rules: list[dict[str, Any]] = field(default_factory=list)

    @classmethod
    def from_dict(cls, rid: str, d: dict[str, Any]) -> "Routine":
        where = f"routines.{rid}"
        d = _mapping(d, where, "a routine (a mapping with a 'components' list)")
        comps = _listing(d.get("components"), f"{where}.components", "a list of components")
        rules = _listing(d.get("rules"), f"{where}.rules", "a list of rules (when/do)")
        for i, r in enumerate(rules):
            if not isinstance(r, dict):
                raise _bad(f"{where}.rules[{i}]", "a rule (a mapping with 'when' and 'do')", r)
            acts = r.get("do")
            for a in (acts if isinstance(acts, list) else [acts]) if acts is not None else []:
                if not isinstance(a, (dict, str)):
                    raise _bad(f"{where}.rules[{i}].do", "an action such as end_routine or {set: {score: 1}}", a)
        return cls(
            id=rid,
            components=[ComponentSpec.from_dict(c, f"{where}.components[{i}]") for i, c in enumerate(comps)],
            duration=d.get("duration"),
            end_if=d.get("end_if"),
            description=str(d.get("description") or ""),
            rules=rules,
        )

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"components": [c.to_dict() for c in self.components]}
        if self.duration is not None:
            d["duration"] = self.duration
        if self.end_if:
            d["end_if"] = self.end_if
        if self.description:
            d["description"] = self.description
        if self.rules:
            d["rules"] = self.rules
        return d


@dataclass
class RoutineRef:
    routine: str
    if_: str | None = None  # skip unless true


@dataclass
class Loop:
    id: str
    children: list["FlowNode"]
    conditions: Any = None        # list[dict] | path | {"factorial": {...}} | None
    order: str = "sequential"     # sequential | random | fullrandom | latin_square | counterbalance
    repeats: Any = 1
    max_repeat: dict[str, int] | None = None   # e.g. {color: 2}: no more than 2 identical in a row
    stop_if: str | None = None    # checked after each iteration
    staircase: dict[str, Any] | None = None    # adaptive procedure (see conditions.Staircase)
    select: Any = None            # subset of rows, e.g. "0:10" or [0, 2, 5]


@dataclass
class Branch:
    condition: str
    then: list["FlowNode"]
    else_: list["FlowNode"] = field(default_factory=list)


@dataclass
class Transition:
    goto: str                       # a state name, or "end" to leave the state machine
    condition: str | None = None    # YAML key "if"; no condition = always (use as the default, last)
    set: dict[str, Any] = field(default_factory=dict)  # variables to assign when taken


@dataclass
class State:
    name: str
    run: list["FlowNode"]
    next: list[Transition] = field(default_factory=list)
    max_visits: int | None = None   # after this many visits, transitions back to this state are skipped and,
                                    # if no other condition holds, the first route to another state is taken
    description: str = ""


@dataclass
class StateMachine:
    """A workflow of states with conditional transitions (if/else between blocks, repeat-until,
    adaptive branching). After a state's contents run, its transitions are checked in order
    and the first one whose condition is true is taken."""
    id: str
    start: str
    states: dict[str, State]
    max_steps: int = 1000


FlowNode = Union[RoutineRef, Loop, Branch, StateMachine]


@dataclass
class DeviceSpec:
    id: str
    type: str
    options: dict[str, Any] = field(default_factory=dict)
    required: bool = True       # abort the session if it cannot connect
    record: bool = True         # write its data streams to disk
    markers: bool = True        # receive broadcast event markers
    calibrate: bool = False     # run calibration at session start

    @classmethod
    def from_dict(cls, d: dict[str, Any], where: str = "device") -> "DeviceSpec":
        known = {"id", "type", "options", "required", "record", "markers", "calibrate"}
        d = _mapping(d, where, "a device (a mapping with id and type)")
        options = _mapping(d.get("options"), f"{where}.options", "the device options (a mapping)")
        options.update({k: v for k, v in d.items() if k not in known})
        return cls(
            id=str(d.get("id", d.get("type", ""))),
            type=str(d.get("type", "")),
            options=options,
            required=bool(d.get("required", True)),
            record=bool(d.get("record", True)),
            markers=bool(d.get("markers", True)),
            calibrate=bool(d.get("calibrate", False)),
        )

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"id": self.id, "type": self.type}
        if self.options:
            d["options"] = self.options
        for k, default in (("required", True), ("record", True), ("markers", True), ("calibrate", False)):
            if getattr(self, k) != default:
                d[k] = getattr(self, k)
        return d


@dataclass
class Experiment:
    name: str
    settings: dict[str, Any]
    routines: dict[str, Routine]
    flow: list[FlowNode]
    devices: list[DeviceSpec] = field(default_factory=list)
    variables: dict[str, Any] = field(default_factory=dict)
    description: str = ""
    measures: list[Any] | None = None   # what the experiment measures (see edge.measures)
    base_dir: Path = field(default_factory=Path.cwd)
    source: dict[str, Any] = field(default_factory=dict)
    path: Path | None = None
    fingerprint: str | None = None
    migrations: list[str] = field(default_factory=list)

    # ---------------------------------------------------------------- loading
    @classmethod
    def from_dict(cls, d: dict[str, Any], base_dir: str | Path | None = None) -> "Experiment":
        """Build an experiment from a document. Anything of the wrong shape raises storage.DocumentError
        naming the place (``routines.trial.components[2]``), never a bare AttributeError."""
        d = _mapping(d, "experiment", "a mapping with name, settings, routines and flow")
        routines = {str(rid): Routine.from_dict(str(rid), r)
                    for rid, r in _mapping(d.get("routines"), "routines", "a mapping of routine name -> routine").items()}
        settings = _mapping(d.get("settings"), "settings")
        for k, v in settings.items():
            if isinstance(DEFAULT_SETTINGS.get(k), dict) and v is not None and not isinstance(v, dict):
                raise _bad(f"settings.{k}", "a mapping", v)
        flow = _listing(d.get("flow"), "flow", "a list of routine names, loops and branches")
        devices = _listing(d.get("devices"), "devices", "a list of devices")
        exp = cls(
            name=str(d.get("name") or "experiment"),
            description=str(d.get("description") or ""),
            settings=deep_merge(DEFAULT_SETTINGS, settings),
            routines=routines,
            flow=[_parse_flow_node(n, i, f"flow[{i}]") for i, n in enumerate(flow)],
            devices=[DeviceSpec.from_dict(x, f"devices[{i}]") for i, x in enumerate(devices)],
            variables=_mapping(d.get("variables"), "variables", "a mapping of variable name -> value"),
            measures=copy.deepcopy(d.get("measures")),
            base_dir=Path(base_dir) if base_dir else Path.cwd(),
            source=copy.deepcopy(d),
        )
        return exp

    @classmethod
    def load(cls, path: str | Path) -> "Experiment":
        """Load a YAML/JSON experiment (migrating older formats). Raises storage.DocumentError
        with line/column information for syntax errors."""
        from .storage import load_document

        loaded = load_document(path)
        exp = cls.from_dict(loaded.doc, base_dir=loaded.path.parent)
        exp.path = loaded.path
        exp.fingerprint = loaded.fingerprint
        exp.migrations = loaded.migrations
        return exp

    def to_dict(self) -> dict[str, Any]:
        from .storage import FORMAT_VERSION
        d = {
            "edge_format": FORMAT_VERSION,
            "name": self.name,
            "description": self.description,
            "settings": self.settings,
            "devices": [d.to_dict() for d in self.devices],
            "variables": self.variables,
            "routines": {rid: r.to_dict() for rid, r in self.routines.items()},
            "flow": [_flow_to_dict(n) for n in self.flow],
        }
        if self.measures is not None:
            d["measures"] = self.measures
        return d

    def save(self, path: str | Path | None = None, check_conflicts: bool = True) -> str:
        """Atomic save with automatic backup. If this experiment was loaded from the same file
        and the file has changed on disk since, storage.ConflictError is raised."""
        from .storage import save_document

        target = Path(path) if path else self.path
        if target is None:
            raise ValueError("no path given")
        expected = self.fingerprint if (check_conflicts and self.path is not None
                                        and Path(target).resolve() == Path(self.path).resolve()) else None
        self.fingerprint = save_document(target, self.to_dict(), expected_fingerprint=expected)
        self.path = Path(target)
        return self.fingerprint

    # ------------------------------------------------------------- validation
    def validate(self) -> list["Issue"]:
        from .components import component_registry
        from .devices import device_registry

        issues: list[Issue] = []
        comp_types = component_registry()
        dev_types = device_registry()

        if not self.flow:
            issues.append(Issue("error", "flow", "the flow is empty: add at least one routine"))

        dev_ids = set()
        for dev in self.devices:
            if dev.id in dev_ids:
                issues.append(Issue("error", f"devices.{dev.id}", "duplicate device id"))
            dev_ids.add(dev.id)
            if dev.type not in dev_types:
                issues.append(Issue("error", f"devices.{dev.id}", f"unknown device type '{dev.type}'",
                                    hint=f"available: {', '.join(sorted(dev_types))}"))
            else:
                try:
                    issues.extend(dev_types[dev.type].validate_options(dev, self))
                except Exception as e:  # a driver's own check must not break validation
                    issues.append(Issue("warning", f"devices.{dev.id}", f"could not check the options: {e}"))

        for rid, routine in self.routines.items():
            ids: set[str] = set()
            for c in routine.components:
                where = f"routines.{rid}.{c.id or '?'}"
                if not c.id:
                    issues.append(Issue("error", where, "component has no id"))
                elif not c.id.isidentifier():
                    issues.append(Issue("error", where, "component id must be a valid identifier (letters, digits, _)"))
                if c.id in ids:
                    issues.append(Issue("error", where, "duplicate component id within routine"))
                ids.add(c.id)
                cls = comp_types.get(c.type)
                if cls is None:
                    issues.append(Issue("error", where, f"unknown component type '{c.type}'",
                                        hint=f"available: {', '.join(sorted(comp_types))}"))
                    continue
                issues.extend(cls.validate_spec(c, where, self))
                if c.type == "code":
                    issues.append(Issue("info", where, "runs Python code on this computer (not sandboxed)",
                                        hint="read it first if the experiment came from someone else"))
                for key in ("start", "duration", "start_if", "stop_if"):
                    v = getattr(c, key)
                    if isinstance(v, str):
                        _check_expr(v if v.startswith("$") else "$" + v, where + "." + key, issues)
                for k, v in c.props.items():
                    if expressions.is_expr(v):
                        _check_expr(v, f"{where}.{k}", issues)
                dev = c.props.get("device")
                if dev and dev not in dev_ids:
                    issues.append(Issue("error", where, f"references unknown device '{dev}'"))
            for c in routine.components:
                if c.only_if:
                    _check_expr(c.only_if if c.only_if.startswith("$") else "$" + c.only_if,
                                f"routines.{rid}.{c.id}.if", issues)
            for i, rule in enumerate(routine.rules):
                where = f"routines.{rid}.rules[{i}]"
                if not isinstance(rule, dict) or "when" not in rule:
                    issues.append(Issue("error", where, "a rule needs 'when' (a condition) and 'do' (actions)"))
                    continue
                w_ = str(rule["when"]) if rule["when"] is not None else ""
                if not w_:
                    issues.append(Issue("error", where, "'when' is empty: give a condition such as $resp.corr == 1"))
                else:
                    _check_expr(w_ if w_.startswith("$") else "$" + w_, where + ".when", issues)
                acts = rule.get("do") or []
                for a in acts if isinstance(acts, list) else [acts]:
                    keys = set(a) if isinstance(a, dict) else {a}
                    bad = keys - RULE_ACTIONS
                    if bad:
                        issues.append(Issue("error", where, f"unknown rule action {', '.join(map(str, bad))}",
                                            hint=", ".join(sorted(RULE_ACTIONS))))
                    if isinstance(a, dict):
                        for k in ("start", "stop"):
                            if k in a and (not isinstance(a[k], str) or a[k] not in ids):
                                issues.append(Issue("error", where, f"{k}: no component '{a[k]}' in this routine"))
            for c in routine.components:
                if c.start_after and c.start_after not in ids:
                    issues.append(Issue("error", f"routines.{rid}.{c.id}", f"start_after refers to unknown component '{c.start_after}'"))
            onsets: dict[Any, list[str]] = {}
            for c in routine.components:
                if (c.props.get("marker") or c.type == "marker") and not c.start_after and c.start_frame is None \
                        and not c.start_if and isinstance(c.start, (int, float)):
                    onsets.setdefault(float(c.start), []).append(c.id)
            for t0, ids_at in onsets.items():
                if len(ids_at) > 1:
                    issues.append(Issue("warning", f"routines.{rid}",
                                        f"markers from {', '.join(ids_at)} all fire at t={t0:g}s; on a TTL line "
                                        "simultaneous codes overwrite each other",
                                        hint="keep one marker per onset, or encode both in one label/code"))
            if not any(c.end_routine or c.duration is not None or c.duration_frames for c in routine.components) \
                    and routine.duration is None and not routine.end_if:
                issues.append(Issue("warning", f"routines.{rid}",
                                    "nothing ends this routine (no duration, end_if, or end_routine component)"))

        used: set[str] = set()

        def walk(nodes: list[FlowNode], where: str) -> None:
            for i, n in enumerate(nodes):
                w = f"{where}[{i}]"
                if isinstance(n, RoutineRef):
                    used.add(n.routine)
                    if n.routine not in self.routines:
                        issues.append(Issue("error", w, f"unknown routine '{n.routine}'"))
                elif isinstance(n, Loop):
                    if n.order not in LOOP_ORDERS:
                        issues.append(Issue("error", w, f"unknown loop order '{n.order}'", hint=", ".join(LOOP_ORDERS)))
                    if not n.children:
                        issues.append(Issue("warning", w, f"loop '{n.id}' has no children"))
                    if isinstance(n.conditions, str) and n.conditions.startswith("$"):
                        _check_expr(n.conditions, w + ".conditions", issues)
                    elif isinstance(n.conditions, str):
                        try:
                            exists = (self.base_dir / n.conditions).exists()
                        except (OSError, ValueError):
                            exists = False
                        if not exists:
                            issues.append(Issue("error", w, f"conditions file not found: {n.conditions[:200]}"))
                    elif n.conditions is not None:
                        from .conditions import load_conditions
                        try:
                            load_conditions(n.conditions, self.base_dir)
                        except Exception as e:
                            issues.append(Issue("error", w + ".conditions", str(e)))
                    issues.extend(_check_loop_numbers(n, w))
                    walk(n.children, f"{w}.{n.id}")
                elif isinstance(n, Branch):
                    _check_expr(n.condition if n.condition.startswith("$") else "$" + n.condition, w + ".if", issues)
                    walk(n.then, w + ".then")
                    walk(n.else_, w + ".else")
                elif isinstance(n, StateMachine):
                    validate_state_machine(n, w, issues)
                    for sname, st in n.states.items():
                        walk(st.run, f"{w}.{n.id}.{sname}")

        walk(self.flow, "flow")
        if not any(i.level == "error" and "expression" in i.message for i in issues):
            from .scope import scope_issues
            try:
                issues.extend(scope_issues(self))
            except Exception:  # the scope check is advisory; never let it break validation
                pass
        for rid in self.routines:
            if rid not in used:
                issues.append(Issue("info", f"routines.{rid}", "routine is defined but never used in the flow"))
        from .measures import validate_measures
        issues.extend(validate_measures(self))
        issues.extend(validate_settings(self.settings))
        data_dir = str((self.settings.get("data") or {}).get("dir") or "data")
        try:
            resolved = (self.base_dir / data_dir).resolve()
            if self.base_dir.resolve() not in resolved.parents:
                issues.append(Issue("warning", "settings.data.dir",
                                    f"data is saved outside the experiment's folder ({resolved})",
                                    hint="keep 'data' (a folder next to the experiment) unless you mean a shared drive"))
        except OSError:
            pass
        try:
            from .pitfalls import pitfall_issues
            issues.extend(pitfall_issues(self))
        except Exception as e:  # advisory checks must never break validation
            issues.append(Issue("info", "experiment", f"some timing/file checks could not run: {e}"))
        return issues

    def iter_routines(self):
        yield from self.routines.values()


LOOP_ORDERS = ("sequential", "random", "fullrandom", "latin_square", "counterbalance")


def validate_state_machine(m: StateMachine, where: str, issues: list["Issue"]) -> None:
    if not m.states:
        issues.append(Issue("error", where, f"state machine '{m.id}' has no states"))
        return
    if m.start not in m.states:
        issues.append(Issue("error", where, f"state machine '{m.id}': start state '{m.start}' does not exist",
                            hint=", ".join(m.states)))
    reachable, todo = set(), [m.start]
    while todo:
        s_ = todo.pop()
        if s_ in reachable or s_ not in m.states:
            continue
        reachable.add(s_)
        todo += [t.goto for t in m.states[s_].next]
    for name, st in m.states.items():
        w = f"{where}.{m.id}.{name}"
        if not st.next:
            issues.append(Issue("info", w, "no transitions: the state machine ends after this state"))
        for i, t in enumerate(st.next):
            if t.goto != "end" and t.goto not in m.states:
                issues.append(Issue("error", w, f"transition {i} goes to unknown state '{t.goto}'",
                                    hint="use 'end' to finish"))
            if t.condition:
                _check_expr(t.condition if t.condition.startswith("$") else "$" + t.condition, f"{w}.next[{i}]", issues)
            if t.condition is None and i < len(st.next) - 1:
                issues.append(Issue("warning", w, f"transition {i} has no condition, so the ones after it never run"))
        if st.next and all(t.condition for t in st.next):
            issues.append(Issue("info", w, "every transition has a condition; if none is true the machine ends"))
        if name not in reachable:
            issues.append(Issue("warning", w, f"state '{name}' can never be reached"))


@dataclass
class Issue:
    level: str   # error | warning | info
    where: str
    message: str
    hint: str = ""

    def __str__(self) -> str:
        s = f"[{self.level.upper()}] {self.where}: {self.message}"
        return s + (f" ({self.hint})" if self.hint else "")

    def to_dict(self) -> dict[str, str]:
        return {"level": self.level, "where": self.where, "message": self.message, "hint": self.hint}


MAX_TRIALS = 1_000_000


def _check_loop_numbers(n: "Loop", w: str) -> list[Issue]:
    """repeats / max_repeat / max_steps must be whole numbers (or expressions), and not absurd."""
    out: list[Issue] = []
    v = n.repeats
    if isinstance(v, str):
        _check_expr(v if v.startswith("$") else "$" + v, f"{w}.repeats", out)
    elif v is not None and (isinstance(v, bool) or not isinstance(v, (int, float)) or v != int(v) or v < 0):
        out.append(Issue("error", f"{w}.repeats", f"repeats must be a whole number (or an expression), not {v!r:.40}"))
    elif isinstance(v, (int, float)) and v > MAX_TRIALS:
        out.append(Issue("error", f"{w}.repeats", f"{int(v)} repetitions is more than any session can run"))
    mr = n.max_repeat
    if mr is not None:
        def _limit_ok(x: Any) -> bool:
            return isinstance(x, int) and not isinstance(x, bool) and x >= 1
        if not isinstance(mr, dict) or not all(_limit_ok(x) or (isinstance(x, dict) and all(map(_limit_ok, x.values())))
                                               for x in mr.values()):
            out.append(Issue("error", f"{w}.max_repeat", "max_repeat maps a column to a limit, e.g. {colour: 2} or "
                                                          "{kind: {deviant: 1}}"))
    if n.select is not None and not isinstance(n.select, (str, int, list)):
        out.append(Issue("error", f"{w}.select", "select must be a number, a list of row numbers or an expression"))
    if n.staircase is not None and not isinstance(n.staircase, dict):
        out.append(Issue("error", f"{w}.staircase", "staircase must be a mapping (start, step, down, up, …)"))
    return out


def _check_expr(src: str, where: str, issues: list[Issue]) -> None:
    if not expressions.is_expr(src):
        return
    try:
        expressions.compile_expr(src[1:])
    except expressions.ExpressionError as e:
        issues.append(Issue("error", where, str(e)))


def window_size(settings: dict[str, Any]) -> tuple[int, int]:
    """``settings.window.size`` as (width, height), or a DocumentError saying what is wrong with it."""
    from .storage import DocumentError
    size = (settings.get("window") or {}).get("size")
    if (isinstance(size, (list, tuple)) and len(size) == 2
            and all(isinstance(v, (int, float)) and not isinstance(v, bool) and v > 0 for v in size)):
        return int(size[0]), int(size[1])
    raise DocumentError(f"settings.window.size must be [width, height] in pixels, e.g. [1280, 720], not {_short(size)}")


def validate_settings(settings: dict[str, Any]) -> list[Issue]:
    """The settings an experiment can't run with: a window size that isn't two numbers, and so on."""
    issues: list[Issue] = []
    win = settings.get("window")
    if not isinstance(win, dict):
        return [Issue("error", "settings.window", "must be a mapping (size, fullscreen, background, units …)")]
    try:
        window_size(settings)
    except ValueError as e:
        issues.append(Issue("error", "settings.window.size", str(e)))
    units = win.get("units")
    if units is not None and not isinstance(units, str):
        issues.append(Issue("error", "settings.window.units", "must be a name such as px, norm, height, deg or cm"))
    for k in ("fullscreen", "vsync"):
        if k in win and not isinstance(win[k], bool):
            issues.append(Issue("error", f"settings.window.{k}", "must be true or false"))
    data = settings.get("data")
    if data is not None and not isinstance(data, dict):
        issues.append(Issue("error", "settings.data", "must be a mapping (dir, …)"))
    elif data and data.get("dir") is not None and not isinstance(data.get("dir"), str):
        issues.append(Issue("error", "settings.data.dir", "must be a folder name"))
    return issues


def _parse_nodes(nodes: Any, ctx: str, where: str = "flow") -> list[FlowNode]:
    if nodes is None:
        return []
    if not isinstance(nodes, list):
        nodes = [nodes]
    return [_parse_flow_node(n, f"{ctx}_{i}", f"{where}[{i}]") for i, n in enumerate(nodes)]


def _parse_flow_node(n: Any, idx: Any, where: str = "flow") -> FlowNode:
    if isinstance(n, str):
        return RoutineRef(n)
    if not isinstance(n, dict):
        raise _bad(where, "a routine name or a mapping with 'routine', 'loop', 'if' or 'statemachine'", n)
    if "routine" in n:
        return RoutineRef(str(n["routine"]), if_=_condition(n.get("if"), f"{where}.if"))
    if "loop" in n:
        lid = str(n["loop"])
        return Loop(
            id=lid,
            children=_parse_nodes(n.get("children"), lid, f"{where}.children"),
            conditions=n.get("conditions"),
            order=str(n.get("order", "sequential")),
            repeats=n.get("repeats", 1),
            max_repeat=n.get("max_repeat"),
            stop_if=n.get("stop_if"),
            staircase=n.get("staircase"),
            select=n.get("select"),
        )
    if "if" in n:
        return Branch(_condition(n["if"], f"{where}.if") or "$False", _parse_nodes(n.get("then"), f"if{idx}", f"{where}.then"),
                      _parse_nodes(n.get("else"), f"else{idx}", f"{where}.else"))
    if "statemachine" in n:
        sid = str(n["statemachine"])
        states = {}
        for name, sd in _mapping(n.get("states"), f"{where}.states", "a mapping of state name -> state").items():
            sw = f"{where}.states.{name}"
            sd = _mapping(sd, sw, "a state (a mapping with 'run' and 'next')")
            run = sd.get("run", [])
            nxt = sd.get("next") or []
            if isinstance(nxt, (str, dict)):
                nxt = [nxt]
            if not isinstance(nxt, list):
                raise _bad(f"{sw}.next", "a state name or a list of transitions", nxt)
            trans = []
            for t in nxt:
                if isinstance(t, str):
                    trans.append(Transition(goto=t, condition=None))
                elif isinstance(t, dict):
                    trans.append(Transition(goto=str(t.get("goto", "end")), condition=_condition(t.get("if"), f"{sw}.next.if"),
                                            set=_mapping(t.get("set"), f"{sw}.next.set")))
                else:
                    raise _bad(f"{sw}.next", "a state name or a mapping with 'goto' and 'if'", t)
            states[str(name)] = State(str(name), _parse_nodes(run, f"{sid}_{name}", f"{sw}.run"), trans,
                                      sd.get("max_visits"), str(sd.get("description") or ""))
        try:
            max_steps = int(n.get("max_steps", 1000))
        except (TypeError, ValueError):
            raise _bad(f"{where}.max_steps", "a number", n.get("max_steps")) from None
        return StateMachine(sid, str(n.get("start") or next(iter(states), "")), states, max_steps)
    raise _bad(where, "a routine name or a mapping with 'routine', 'loop', 'if' or 'statemachine'", n)


def _flow_to_dict(n: FlowNode) -> Any:
    if isinstance(n, RoutineRef):
        return n.routine if not n.if_ else {"routine": n.routine, "if": n.if_}
    if isinstance(n, Loop):
        d: dict[str, Any] = {"loop": n.id}
        for k in ("conditions", "order", "repeats", "max_repeat", "stop_if", "staircase", "select"):
            v = getattr(n, k)
            if v is not None and not (k == "order" and v == "sequential") and not (k == "repeats" and v == 1):
                d[k] = v
        d["children"] = [_flow_to_dict(c) for c in n.children]
        return d
    if isinstance(n, Branch):
        d = {"if": n.condition, "then": [_flow_to_dict(c) for c in n.then]}
        if n.else_:
            d["else"] = [_flow_to_dict(c) for c in n.else_]
        return d
    if isinstance(n, StateMachine):
        states = {}
        for name, st in n.states.items():
            sd: dict[str, Any] = {"run": [_flow_to_dict(c) for c in st.run]}
            nxt = []
            for t in st.next:
                td: dict[str, Any] = {}
                if t.condition:
                    td["if"] = t.condition
                td["goto"] = t.goto
                if t.set:
                    td["set"] = t.set
                nxt.append(td)
            if nxt:
                sd["next"] = nxt
            if st.max_visits:
                sd["max_visits"] = st.max_visits
            if st.description:
                sd["description"] = st.description
            states[name] = sd
        out: dict[str, Any] = {"statemachine": n.id, "start": n.start, "states": states}
        if n.max_steps != 1000:
            out["max_steps"] = n.max_steps
        return out
    raise TypeError(n)
