"""The EDGE experiment model.

An experiment is a plain data document (YAML or JSON) so it can be produced by
the visual builder, written by hand, generated by scripts, diffed in git and
validated before anyone sits in front of a screen.

    name: Stroop
    settings: {window: {size: [1280, 720], background: "#202020"}}
    devices:
      - {id: et, type: gazepoint}
      - {id: lsl, type: lsl_markers}
    routines:
      trial:
        components:
          - {id: word, type: text, text: "$word", color: "$ink", start: 0.5}
          - {id: resp, type: keyboard, keys: [r, g, b], start: 0.5, end_routine: true,
             correct: "$correct_key"}
    flow:
      - instructions
      - loop: trials
        conditions: stroop.csv
        order: random
        repeats: 2
        children: [trial]

See docs/EXPERIMENT_FORMAT.md for the full reference.
"""

from __future__ import annotations

import copy
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Union

import yaml

from . import expressions

FORMAT_VERSION = 1

DEFAULT_SETTINGS: dict[str, Any] = {
    "window": {
        "size": [1280, 720],
        "fullscreen": False,
        "screen": 0,
        "background": "#000000",
        "units": "px",           # px | norm | height | deg
        "refresh_rate": None,    # None = measure at startup
        "vsync": True,
        "monitor": {"width_cm": 53.0, "distance_cm": 60.0},
    },
    "data": {
        "dir": "data",
        "filename": "{participant}_{session}_{experiment}_{date}",
        "save_frame_log": True,
    },
    "participant": {"participant": "001", "session": "1"},
    "timing": {
        "frame_drop_tolerance": 1.5,   # a frame is "dropped" if interval > tolerance * expected
    },
    "seed": None,
}

# Keys that belong to the component's scheduling rather than its properties.
SCHEDULE_KEYS = {
    "id", "type", "start", "start_frame", "start_after", "start_if",
    "duration", "duration_frames", "stop_if", "end_routine", "disabled", "save",
}


def deep_merge(base: dict, override: dict) -> dict:
    out = copy.deepcopy(base)
    for k, v in (override or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = copy.deepcopy(v)
    return out


@dataclass
class ComponentSpec:
    id: str
    type: str
    start: Any = 0.0
    start_frame: int | None = None
    start_after: str | None = None
    start_if: str | None = None
    duration: Any = None
    duration_frames: int | None = None
    stop_if: str | None = None
    end_routine: bool = False
    disabled: Any = False
    save: bool = True
    props: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "ComponentSpec":
        props = {k: v for k, v in d.items() if k not in SCHEDULE_KEYS}
        return cls(
            id=str(d.get("id", "")),
            type=str(d.get("type", "")),
            start=d.get("start", 0.0),
            start_frame=d.get("start_frame"),
            start_after=d.get("start_after"),
            start_if=d.get("start_if"),
            duration=d.get("duration"),
            duration_frames=d.get("duration_frames"),
            stop_if=d.get("stop_if"),
            end_routine=bool(d.get("end_routine", False)),
            disabled=d.get("disabled", False),
            save=bool(d.get("save", True)),
            props=props,
        )

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"id": self.id, "type": self.type}
        defaults = ComponentSpec(id="", type="")
        for k in SCHEDULE_KEYS - {"id", "type"}:
            v = getattr(self, k)
            if v != getattr(defaults, k):
                d[k] = v
        d.update(self.props)
        return d


@dataclass
class Routine:
    id: str
    components: list[ComponentSpec] = field(default_factory=list)
    duration: Any = None      # hard cap in seconds (number or expression)
    end_if: str | None = None  # expression checked every frame
    description: str = ""

    @classmethod
    def from_dict(cls, rid: str, d: dict[str, Any]) -> "Routine":
        return cls(
            id=rid,
            components=[ComponentSpec.from_dict(c) for c in d.get("components", [])],
            duration=d.get("duration"),
            end_if=d.get("end_if"),
            description=d.get("description", ""),
        )

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"components": [c.to_dict() for c in self.components]}
        if self.duration is not None:
            d["duration"] = self.duration
        if self.end_if:
            d["end_if"] = self.end_if
        if self.description:
            d["description"] = self.description
        return d


@dataclass
class RoutineRef:
    routine: str
    if_: str | None = None  # skip unless true


@dataclass
class Loop:
    id: str
    children: list["FlowNode"]
    conditions: Any = None        # list[dict] | path | {"factorial": {...}} | None
    order: str = "sequential"     # sequential | random | fullrandom | latin_square | counterbalance
    repeats: Any = 1
    max_repeat: dict[str, int] | None = None   # e.g. {color: 2}: no more than 2 identical in a row
    stop_if: str | None = None    # checked after each iteration
    staircase: dict[str, Any] | None = None    # adaptive procedure (see conditions.Staircase)
    select: Any = None            # subset of rows, e.g. "0:10" or [0, 2, 5]


@dataclass
class Branch:
    condition: str
    then: list["FlowNode"]
    else_: list["FlowNode"] = field(default_factory=list)


FlowNode = Union[RoutineRef, Loop, Branch]


@dataclass
class DeviceSpec:
    id: str
    type: str
    options: dict[str, Any] = field(default_factory=dict)
    required: bool = True       # abort the session if it cannot connect
    record: bool = True         # write its data streams to disk
    markers: bool = True        # receive broadcast event markers
    calibrate: bool = False     # run calibration at session start

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "DeviceSpec":
        known = {"id", "type", "options", "required", "record", "markers", "calibrate"}
        options = dict(d.get("options", {}))
        options.update({k: v for k, v in d.items() if k not in known})
        return cls(
            id=str(d.get("id", d.get("type", ""))),
            type=str(d.get("type", "")),
            options=options,
            required=bool(d.get("required", True)),
            record=bool(d.get("record", True)),
            markers=bool(d.get("markers", True)),
            calibrate=bool(d.get("calibrate", False)),
        )

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"id": self.id, "type": self.type}
        if self.options:
            d["options"] = self.options
        for k, default in (("required", True), ("record", True), ("markers", True), ("calibrate", False)):
            if getattr(self, k) != default:
                d[k] = getattr(self, k)
        return d


@dataclass
class Experiment:
    name: str
    settings: dict[str, Any]
    routines: dict[str, Routine]
    flow: list[FlowNode]
    devices: list[DeviceSpec] = field(default_factory=list)
    variables: dict[str, Any] = field(default_factory=dict)
    description: str = ""
    base_dir: Path = field(default_factory=Path.cwd)
    source: dict[str, Any] = field(default_factory=dict)

    # ---------------------------------------------------------------- loading
    @classmethod
    def from_dict(cls, d: dict[str, Any], base_dir: str | Path | None = None) -> "Experiment":
        routines = {rid: Routine.from_dict(rid, r or {}) for rid, r in (d.get("routines") or {}).items()}
        exp = cls(
            name=str(d.get("name", "experiment")),
            description=d.get("description", ""),
            settings=deep_merge(DEFAULT_SETTINGS, d.get("settings") or {}),
            routines=routines,
            flow=[_parse_flow_node(n, i) for i, n in enumerate(d.get("flow") or [])],
            devices=[DeviceSpec.from_dict(x) for x in (d.get("devices") or [])],
            variables=dict(d.get("variables") or {}),
            base_dir=Path(base_dir) if base_dir else Path.cwd(),
            source=copy.deepcopy(d),
        )
        return exp

    @classmethod
    def load(cls, path: str | Path) -> "Experiment":
        path = Path(path)
        text = path.read_text(encoding="utf-8")
        data = json.loads(text) if path.suffix.lower() == ".json" else yaml.safe_load(text)
        if not isinstance(data, dict):
            raise ValueError(f"{path}: experiment file must contain a mapping at the top level")
        return cls.from_dict(data, base_dir=path.parent)

    def to_dict(self) -> dict[str, Any]:
        return {
            "edge_format": FORMAT_VERSION,
            "name": self.name,
            "description": self.description,
            "settings": self.settings,
            "devices": [d.to_dict() for d in self.devices],
            "variables": self.variables,
            "routines": {rid: r.to_dict() for rid, r in self.routines.items()},
            "flow": [_flow_to_dict(n) for n in self.flow],
        }

    def save(self, path: str | Path) -> None:
        path = Path(path)
        d = self.to_dict()
        if path.suffix.lower() == ".json":
            path.write_text(json.dumps(d, indent=2), encoding="utf-8")
        else:
            path.write_text(yaml.safe_dump(d, sort_keys=False, allow_unicode=True), encoding="utf-8")

    # ------------------------------------------------------------- validation
    def validate(self) -> list["Issue"]:
        from .components import component_registry
        from .devices import device_registry

        issues: list[Issue] = []
        comp_types = component_registry()
        dev_types = device_registry()

        if not self.flow:
            issues.append(Issue("error", "flow", "the flow is empty: add at least one routine"))

        dev_ids = set()
        for dev in self.devices:
            if dev.id in dev_ids:
                issues.append(Issue("error", f"devices.{dev.id}", "duplicate device id"))
            dev_ids.add(dev.id)
            if dev.type not in dev_types:
                issues.append(Issue("error", f"devices.{dev.id}", f"unknown device type '{dev.type}'",
                                    hint=f"available: {', '.join(sorted(dev_types))}"))

        for rid, routine in self.routines.items():
            ids: set[str] = set()
            for c in routine.components:
                where = f"routines.{rid}.{c.id or '?'}"
                if not c.id:
                    issues.append(Issue("error", where, "component has no id"))
                elif not c.id.isidentifier():
                    issues.append(Issue("error", where, "component id must be a valid identifier (letters, digits, _)"))
                if c.id in ids:
                    issues.append(Issue("error", where, "duplicate component id within routine"))
                ids.add(c.id)
                cls = comp_types.get(c.type)
                if cls is None:
                    issues.append(Issue("error", where, f"unknown component type '{c.type}'",
                                        hint=f"available: {', '.join(sorted(comp_types))}"))
                    continue
                issues.extend(cls.validate_spec(c, where, self))
                for key in ("start", "duration", "start_if", "stop_if"):
                    v = getattr(c, key)
                    if isinstance(v, str):
                        _check_expr(v if v.startswith("$") else "$" + v, where + "." + key, issues)
                for k, v in c.props.items():
                    if expressions.is_expr(v):
                        _check_expr(v, f"{where}.{k}", issues)
                dev = c.props.get("device")
                if dev and dev not in dev_ids:
                    issues.append(Issue("error", where, f"references unknown device '{dev}'"))
            for c in routine.components:
                if c.start_after and c.start_after not in ids:
                    issues.append(Issue("error", f"routines.{rid}.{c.id}", f"start_after refers to unknown component '{c.start_after}'"))
            onsets: dict[Any, list[str]] = {}
            for c in routine.components:
                if (c.props.get("marker") or c.type == "marker") and not c.start_after and c.start_frame is None \
                        and not c.start_if and isinstance(c.start, (int, float)):
                    onsets.setdefault(float(c.start), []).append(c.id)
            for t0, ids_at in onsets.items():
                if len(ids_at) > 1:
                    issues.append(Issue("warning", f"routines.{rid}",
                                        f"markers from {', '.join(ids_at)} all fire at t={t0:g}s; on a TTL line "
                                        "simultaneous codes overwrite each other",
                                        hint="keep one marker per onset, or encode both in one label/code"))
            if not any(c.end_routine or c.duration is not None or c.duration_frames for c in routine.components) \
                    and routine.duration is None and not routine.end_if:
                issues.append(Issue("warning", f"routines.{rid}",
                                    "nothing ends this routine (no duration, end_if, or end_routine component)"))

        used: set[str] = set()

        def walk(nodes: list[FlowNode], where: str) -> None:
            for i, n in enumerate(nodes):
                w = f"{where}[{i}]"
                if isinstance(n, RoutineRef):
                    used.add(n.routine)
                    if n.routine not in self.routines:
                        issues.append(Issue("error", w, f"unknown routine '{n.routine}'"))
                elif isinstance(n, Loop):
                    if n.order not in LOOP_ORDERS:
                        issues.append(Issue("error", w, f"unknown loop order '{n.order}'", hint=", ".join(LOOP_ORDERS)))
                    if not n.children:
                        issues.append(Issue("warning", w, f"loop '{n.id}' has no children"))
                    if isinstance(n.conditions, str):
                        p = (self.base_dir / n.conditions)
                        if not p.exists():
                            issues.append(Issue("error", w, f"conditions file not found: {p}"))
                    walk(n.children, f"{w}.{n.id}")
                elif isinstance(n, Branch):
                    _check_expr(n.condition if n.condition.startswith("$") else "$" + n.condition, w + ".if", issues)
                    walk(n.then, w + ".then")
                    walk(n.else_, w + ".else")

        walk(self.flow, "flow")
        for rid in self.routines:
            if rid not in used:
                issues.append(Issue("info", f"routines.{rid}", "routine is defined but never used in the flow"))
        return issues

    def iter_routines(self):
        yield from self.routines.values()


LOOP_ORDERS = ("sequential", "random", "fullrandom", "latin_square", "counterbalance")


@dataclass
class Issue:
    level: str   # error | warning | info
    where: str
    message: str
    hint: str = ""

    def __str__(self) -> str:
        s = f"[{self.level.upper()}] {self.where}: {self.message}"
        return s + (f" ({self.hint})" if self.hint else "")

    def to_dict(self) -> dict[str, str]:
        return {"level": self.level, "where": self.where, "message": self.message, "hint": self.hint}


def _check_expr(src: str, where: str, issues: list[Issue]) -> None:
    if not expressions.is_expr(src):
        return
    try:
        expressions.compile_expr(src[1:])
    except expressions.ExpressionError as e:
        issues.append(Issue("error", where, str(e)))


def _parse_nodes(nodes: Any, ctx: str) -> list[FlowNode]:
    if nodes is None:
        return []
    if not isinstance(nodes, list):
        nodes = [nodes]
    return [_parse_flow_node(n, f"{ctx}_{i}") for i, n in enumerate(nodes)]


def _parse_flow_node(n: Any, idx: Any) -> FlowNode:
    if isinstance(n, str):
        return RoutineRef(n)
    if not isinstance(n, dict):
        raise ValueError(f"invalid flow entry: {n!r}")
    if "routine" in n:
        return RoutineRef(str(n["routine"]), if_=n.get("if"))
    if "loop" in n:
        lid = str(n["loop"])
        return Loop(
            id=lid,
            children=_parse_nodes(n.get("children"), lid),
            conditions=n.get("conditions"),
            order=str(n.get("order", "sequential")),
            repeats=n.get("repeats", 1),
            max_repeat=n.get("max_repeat"),
            stop_if=n.get("stop_if"),
            staircase=n.get("staircase"),
            select=n.get("select"),
        )
    if "if" in n:
        return Branch(str(n["if"]), _parse_nodes(n.get("then"), f"if{idx}"), _parse_nodes(n.get("else"), f"else{idx}"))
    raise ValueError(f"flow entry must be a routine name or contain 'routine', 'loop' or 'if': {n!r}")


def _flow_to_dict(n: FlowNode) -> Any:
    if isinstance(n, RoutineRef):
        return n.routine if not n.if_ else {"routine": n.routine, "if": n.if_}
    if isinstance(n, Loop):
        d: dict[str, Any] = {"loop": n.id}
        for k in ("conditions", "order", "repeats", "max_repeat", "stop_if", "staircase", "select"):
            v = getattr(n, k)
            if v is not None and not (k == "order" and v == "sequential") and not (k == "repeats" and v == 1):
                d[k] = v
        d["children"] = [_flow_to_dict(c) for c in n.children]
        return d
    if isinstance(n, Branch):
        d = {"if": n.condition, "then": [_flow_to_dict(c) for c in n.then]}
        if n.else_:
            d["else"] = [_flow_to_dict(c) for c in n.else_]
        return d
    raise TypeError(n)
